import { api, LightningElement, track } from 'lwc';
import { NavigationMixin } from 'lightning/navigation';
import Images from '@salesforce/resourceUrl/images';
import Images1 from '@salesforce/resourceUrl/images1';
import FORM_FACTOR from '@salesforce/client/formFactor';
import { ShowToastEvent } from 'lightning/platformShowToastEvent';

const verderaData = () =>  {
	return [
			{
				show: true,
				productCode: "0000010",
				name: "Papel, plástico e tecidos contaminados",
				img: Images + '/produto1.png',
				stockUn: "TON",
				family: "SOLIDOS",
				center: [
					{
						show: true,
						name: "Regional SUL",
						stockLabel: '13 TON',
						stock: 60,
						listPrice: 10,
						taxPrice : 10,
						jurosPrice : 10,
						campaignPrice : 10,
						showLastBuy: true,
						showCart: false,
						lastBuy: "10/05/2022",
						leadTime: 5,
						quantity: 0,
						discount: 0,
						totalPrice: 0
					},
				]
			},
			{
				show: true,
				productCode: "0000020",
				name: "Areia de Fundição, Lamas Contaminadas",
				img: Images + '/produto2.png',
				stockUn: "TON",
				family: "SOLIDOS",
				center: [
					{
						show: true,
						name: "Regional LESTE",
						stockLabel: '24 TON',
						stock: 30,
						listPrice: 20,
						taxPrice : 10,
						jurosPrice : 10,
						campaignPrice : 10,
						showLastBuy: true,
						showCart: false,
						lastBuy: "10/05/2022",
						leadTime: 5,
						quantity: 0,
						discount: 0,
						totalPrice: 0
					},
				]
			},
			{
				show: true,
				productCode: "0000030",
				name: "Borras de Tinta e oleosas",
				img: Images + '/produto3.png',
				stockUn: "TON",
				family: "LIQUIDOS",
				center: [
					{
						show: true,
						name: "Regional SUL",
						stockLabel: '43 TON',
						stock: 39,
						listPrice: 20,
						taxPrice : 10,
						jurosPrice : 10,
						campaignPrice : 10,
						showLastBuy: true,
						showCart: false,
						lastBuy: "10/05/2022",
						leadTime: 5,
						quantity: 0,
						discount: 0,
						totalPrice: 0
					},
				]
			},
			{
				show: true,
				productCode: "0000040",
				name: "Cavaco de madeira, casca de arroz",
				img: Images + '/produto4.png',
				stockUn: "TON",
				family: "BIOMASSA",
				center: [
					{
						show: true,
						name: "Regional OESTE",
						stockLabel: '21 TON',
						stock: 60,
						listPrice: 10,
						taxPrice : 10,
						jurosPrice : 10,
						campaignPrice : 10,
						showLastBuy: true,
						showCart: false,
						lastBuy: "10/05/2022",
						leadTime: 5,
						quantity: 0,
						discount: 0,
						totalPrice: 0
					},
				]
			},
			{
				show: true,
				productCode: "0000050",
				name: "Pneus emborrachados",
				img: Images + '/produto5.png',
				stockUn: "TON",
				family: "PNEUS",
				center: [
					{
						show: true,
						name: "Regional SUL",
						stockLabel: '43 TON',
						stock: 60,
						listPrice: 10,
						taxPrice : 10,
						jurosPrice : 10,
						campaignPrice : 10,
						showLastBuy: true,
						showCart: false,
						lastBuy: "10/05/2022",
						leadTime: 5,
						quantity: 0,
						discount: 0,
						totalPrice: 0
					},
					{
						show: true,
						name: "Regional NORTE",
						stockLabel: '65 TON',
						stock: 65,
						listPrice: 12,
						taxPrice : 10,
						jurosPrice : 10,
						campaignPrice : 10,
						showLastBuy: true,
						showCart: false,
						lastBuy: "11/05/2022",
						leadTime: 5,
						quantity: 0,
						discount: 0,
						totalPrice: 0
					}
				]
			}
		];
}

const haraldData = () =>  {
	return [
			{
				show: true,
				productCode: "0000010",
				name: "Chipshow TOP Avelã Gotas 1,01kg",
				img: Images + '/chipshow.png',
				stockUn: "UN",
				family: "Melken",
				center: [
					{
						show: true,
						name: "RANQUINES DOCES",
						stockLabel: 'Positivo',
						stock: 60,
						listPrice: 10,
						showLastBuy: true,
						showCart: false,
						lastBuy: "10/05/2022",
						leadTime: 5,
						quantity: 0,
						discount: 0,
						totalPrice: 0
					},
				]
			},
			{
				show: true,
				productCode: "0000010",
				name: "Confeiteiro ao Leite Barra 2,100 kg",
				img: Images + '/confeiteiro.png',
				stockUn: "UN",
				family: "Cobertura",
				center: [
					{
						show: true,
						name: "RANQUINES DOCES",
						stockLabel: 'Positivo',
						stock: 30,
						listPrice: 20,
						showLastBuy: true,
						showCart: false,
						lastBuy: "10/05/2022",
						leadTime: 5,
						quantity: 0,
						discount: 0,
						totalPrice: 0
					},
				]
			},
			{
				show: true,
				productCode: "0000010",
				name: "Confeiteiro ao Leite Gotas 1,01kg",
				img: Images + '/confeiteiro2.png',
				stockUn: "UN",
				family: "Cobertura",
				center: [
					{
						show: true,
						name: "RANQUINES DOCES",
						stockLabel: 'Positivo',
						stock: 39,
						listPrice: 20,
						showLastBuy: true,
						showCart: false,
						lastBuy: "10/05/2022",
						leadTime: 5,
						quantity: 0,
						discount: 0,
						totalPrice: 0
					},
				]
			},
			{
				show: true,
				productCode: "0000010",
				name: "Confeiteiro Blend Barra 1,01kg",
				img: Images + '/blendBarra.png',
				stockUn: "UN",
				family: "Melken",
				center: [
					{
						show: true,
						name: "RANQUINES DOCES",
						stockLabel: 'Positivo',
						stock: 60,
						listPrice: 10,
						showLastBuy: true,
						showCart: false,
						lastBuy: "10/05/2022",
						leadTime: 5,
						quantity: 0,
						discount: 0,
						totalPrice: 0
					},
				]
			},
			{
				show: true,
				productCode: "0000010",
				name: "Granulé de Chocolate 400 g",
				img: Images + '/melken2.png',
				stockUn: "UN",
				family: "Melken",
				center: [
					{
						show: true,
						name: "MAGRI IMPORTS",
						stockLabel: 'Positivo',
						stock: 60,
						listPrice: 10,
						showLastBuy: true,
						showCart: false,
						lastBuy: "10/05/2022",
						leadTime: 5,
						quantity: 0,
						discount: 0,
						totalPrice: 0
					},
					{
						show: true,
						name: "RONDO CHOCOLATES",
						stockLabel: 'Positivo',
						stock: 65,
						listPrice: 12,
						showLastBuy: true,
						showCart: false,
						lastBuy: "11/05/2022",
						leadTime: 5,
						quantity: 0,
						discount: 0,
						totalPrice: 0
					}
				]
			},
			
			{
				show: true,
				productCode: "0000020",
				name: "Melken ao Leite Gotas 2,05kg",
				img: Images + '/gotas1.png',
				stockUn: "UN",
				family: "Melken",
				center: [
					{
						show: true,
						name: "RANQUINES DOCES",
						stockLabel: 'Positivo',
						stock: 1000,
						listPrice: 23,
						showLastBuy: false,
						showCart: false,
						lastBuy: "",
						leadTime: 7,
						quantity: 0,
						discount: 0,
						totalPrice: 0
					},
					{
						show: true,
						name: "RONDO CHOCOLATES",
						stockLabel: 'Positivo',
						stock: 1300,
						listPrice: 21,
						showLastBuy: false,
						showCart: false,
						lastBuy: "",
						leadTime: 8,
						quantity: 0,
						discount: 0,
						totalPrice: 0
					}
				]
			},
			{
				show: true,
				productCode: "0000030",
				name: "Melken Gotas de Chocolate  - 400g",
				img: Images + '/belga400.png',
				stockUn: "UN",
				family: "Cobertura",
				center: [
					{
						show: true,
						name: "MAGRI IMPORTS",
						stockLabel: 'Positivo',
						stock: 10,
						listPrice: 21,
						showLastBuy: true,
						showCart: false,
						lastBuy: "15/05/2022",
						leadTime: 15,
						quantity: 0,
						discount: 0,
						totalPrice: 0
					},
					{
						show: true,
						name: "RONDO GOTAS DE CHOCOLATE",
						stockLabel: 'Positivo',
						stock: 5,
						listPrice: 23,
						showLastBuy: false,
						showCart: false,
						lastBuy: "11/05/2022",
						leadTime: 13,
						quantity: 0,
						discount: 0,
						totalPrice: 0
					}
				]
			},
			{
				show: true,
				productCode: "0000040",
				name: "Melken Meio Amargo Gotas 2,05kg",
				img: Images + '/melken3.png',
				stockUn: "UN",
				family: "Cobertura",
				center: [
					{
						show: true,
						name: "LOJA MAFRA",
						stockLabel: 'Positivo',
						stock: 20,
						listPrice: 30,
						showLastBuy: true,
						showCart: false,
						lastBuy: "09/05/2022",
						leadTime: 5,
						quantity: 0,
						discount: 0,
						totalPrice: 0
					},
					{
						show: true,
						name: "LOJA TEIXEIRA",
						stockLabel: 'Positivo',
						stock: 2,
						listPrice: 40,
						showLastBuy: true,
						showCart: false,
						lastBuy: "15/05/2022",
						leadTime: 5,
						quantity: 0,
						discount: 0,
						totalPrice: 0
					}
				]
			},
			{
				show: true,
				productCode: "0000050",
				name: "Cobertura Churros Melken 1,01kg",
				img: Images + '/cobertura1.png',
				stockUn: "UN",
				family: "Confeiteiro",
				center: [
					{
						show: true,
						name: "MAGRI IMPORTS",
						stockLabel: 'Positivo',
						stock: 200,
						listPrice: 115,
						showLastBuy: true,
						showCart: false,
						lastBuy: "10/05/2022",
						leadTime: 5,
						quantity: 0,
						discount: 0,
						totalPrice: 0
					},
					{
						show: true,
						name: "RONDO GOTAS DE CHOCOLATE",
						stockLabel: 'Positivo',
						stock: 300,
						listPrice: 117,
						showLastBuy: true,
						showCart: false,
						lastBuy: "11/05/2022",
						leadTime: 5,
						quantity: 0,
						discount: 0,
						totalPrice: 0
					}
				]
			}
		];
}
const iharaData = () =>  {
	return [
			{
				show: true,
				productCode: "0000010",
				name: "ABSOLUTO FIX 10L",
				img: Images + '/absoluto.png',
				stockUn: "Pallet",
				qtdPallet: 40,
				family: "FUNGICIDA",
				center: [
					{
						show: true,
						name: "SINOP",
						stockLabel: '10 Pallet',
						stock: 60,
						listPrice: 100,
						taxPrice : 10,
						jurosPrice : 10,
						campaignPrice : 10,
						showLastBuy: true,
						showCart: false,
						lastBuy: "10/05/2022",
						leadTime: 5,
						quantity: 0,
						discount: 0,
						totalPrice: 0
					},
				]
			},
			{
				show: true,
				productCode: "0000010",
				name: "APPROVE 10L",
				img: Images + '/approve.png',
				qtdPallet: 30,
				stockUn: "Pallet",
				family: "FUNGICIDA",
				center: [
					{
						show: true,
						name: "SINOP",
						stock: 60,
						listPrice: 100,
						taxPrice : 10,
						jurosPrice : 10,
						campaignPrice : 10,
						showLastBuy: true,
						showCart: false,
						lastBuy: "22/06/2022",
						leadTime: 5,
						quantity: 0,
						discount: 0,
						totalPrice: 0
					},
				]
			},
			{
				show: true,
				productCode: "0000010",
				name: "BOLD 5L",
				img: Images + '/bold.png',
				qtdPallet: 10,
				stockUn: "Pallet",
				family: "INSETICIDAS",
				center: [
					{
						show: true,
						name: "SINOP",
						stock: 60,
						listPrice: 100,
						taxPrice : 10,
						jurosPrice : 10,
						campaignPrice : 10,
						showLastBuy: true,
						showCart: false,
						lastBuy: "22/06/2022",
						leadTime: 5,
						quantity: 0,
						discount: 0,
						totalPrice: 0
					}
				]
			},
			{
				show: true,
				productCode: "0000010",
				name: "BURNER 1L",
				img: Images + '/burner.png',
				qtdPallet: 10,
				stockUn: "Pallet",
				family: "HERBICIDAS",
				center: [
					{
						show: true,
						name: "SORRISO",
						stock: 60,
						listPrice: 100,
						taxPrice : 10,
						jurosPrice : 10,
						campaignPrice : 10,
						showLastBuy: true,
						showCart: false,
						lastBuy: "22/06/2022",
						leadTime: 5,
						quantity: 0,
						discount: 0,
						totalPrice: 0
					}
				]
			},
		];
}
const viterData = () =>  {
	return [
			{
				show: true,
				productCode: "0000010",
				name: "Optmix S4 3:1",
				img: Images1 + '/optmix.svg',
				stockUn: "Granel",
				qtdPallet: 10,
				family: "Estrategico",
				showRecomendation: true,
				recomendation: {
					quantity : 10,
					unitPrice:  8.76
				},
				center: [
					{
						show: true,
						name: "Itapeva (SP)",
						stockLabel: '10 Qtd',
						stock: 60,
						listPrice: 100,
						taxPrice : 10,
						jurosPrice : 10,
						campaignPrice : 10,
						showLastBuy: true,
						showCart: false,
						lastBuy: "10/05/2022",
						leadTime: 5,
						quantity: 0,
						discount: 0,
						totalPrice: 0
					},
				]
			},
			{
				show: true,
				productCode: "0000020",
				name: "Calcário Itaú",
				img: Images1 + '/calcario.svg',
				stockUn: "Granel",
				qtdPallet: 30,
				family: "N/A",
				showRecomendation: true,
				recomendation: {
					quantity : 14,
					unitPrice:  18.76
				},
				center: [
					{
						show: true,
						name: "Itaú de Minas (MG)",
						stock: 60,
						listPrice: 18.76,
						taxPrice : 2,
						jurosPrice : 3,
						campaignPrice : 9,
						showLastBuy: true,
						showCart: false,
						lastBuy: "22/06/2022",
						leadTime: 5,
						quantity: 0,
						discount: 0,
						totalPrice: 0
					},
					{
						show: true,
						name: "Itapeva (SP)",
						stock: 60,
						listPrice: 18.76,
						taxPrice : 2,
						jurosPrice : 3,
						campaignPrice : 9,
						showLastBuy: true,
						showCart: false,
						lastBuy: "22/06/2022",
						leadTime: 5,
						quantity: 0,
						discount: 0,
						totalPrice: 0
					},
				]
			},
			{
				show: true,
				productCode: "0000030",
				name: "CalFértil HD",
				img: Images1 + '/calfertil.svg',
				qtdPallet: 45,
				stockUn: "20 Kg",
				family: "Escala",
				showRecomendation: false,
				recomendation: {
					quantity : 10,
					unitPrice:  8.76
				},
				center: [
					{
						show: true,
						name: "Itaú de Minas (MG)",
						stock: 45,
						listPrice: 34,
						taxPrice : 12.12,
						jurosPrice : 10,
						campaignPrice : 10,
						showLastBuy: true,
						showCart: false,
						lastBuy: "22/06/2022",
						leadTime: 5,
						quantity: 0,
						discount: 0,
						totalPrice: 0
					},
					{
						show: true,
						name: "Itapeva (SP)",
						stock: 45,
						listPrice: 34,
						taxPrice : 12.12,
						jurosPrice : 10,
						campaignPrice : 10,
						showLastBuy: true,
						showCart: false,
						lastBuy: "22/06/2022",
						leadTime: 5,
						quantity: 0,
						discount: 0,
						totalPrice: 0
					}
				]
			},
			{
				show: true,
				productCode: "0000040",
				name: "SUNGARD",
				img: Images1 + '/sungard.png',
				qtdPallet: 12,
				stockUn: "20 Kg",
				family: "N/A",
				showRecomendation: false,
				recomendation: {
					quantity : 10,
					unitPrice:  8.76
				},
				center: [
					{
						show: true,
						name: "Itaú de Minas (MG)",
						stock: 12,
						listPrice: 54.42,
						taxPrice : 10,
						jurosPrice : 10,
						campaignPrice : 10,
						showLastBuy: true,
						showCart: false,
						lastBuy: "22/06/2022",
						leadTime: 5,
						quantity: 0,
						discount: 0,
						totalPrice: 0
					}
				]
			},
		];
}
const forusData = () =>  {
	return [
			{
				show: true,
				productCode: "0000010",
				name: "POLIPLUS XTRA GREEN",
				img: Images1 + '/SOYAPRIMEGREEN.png',
				stockUn: "Qtd",
				qtdPallet: 10,
				family: "SOILCARE",
				showRecomendation: true,
				recomendation: {
					quantity : 10,
					unitPrice:  8.76
				},
				center: [
					{
						show: true,
						name: "SINOP",
						stockLabel: '10 Qtd',
						stock: 60,
						listPrice: 100,
						taxPrice : 10,
						jurosPrice : 10,
						campaignPrice : 10,
						showLastBuy: true,
						showCart: false,
						lastBuy: "10/05/2022",
						leadTime: 5,
						quantity: 0,
						discount: 0,
						totalPrice: 0
					},
				]
			},
			{
				show: true,
				productCode: "0000020",
				name: "VALIENTE",
				img: Images1 + '/SOYAPRIMEGREEN.png',
				stockUn: "Qtd",
				qtdPallet: 30,
				family: "SOILCARE",
				showRecomendation: true,
				recomendation: {
					quantity : 14,
					unitPrice:  18.76
				},
				center: [
					{
						show: true,
						name: "SINOP",
						stock: 60,
						listPrice: 18.76,
						taxPrice : 2,
						jurosPrice : 3,
						campaignPrice : 9,
						showLastBuy: true,
						showCart: false,
						lastBuy: "22/06/2022",
						leadTime: 5,
						quantity: 0,
						discount: 0,
						totalPrice: 0
					},
				]
			},
			{
				show: true,
				productCode: "0000030",
				name: "SOYA SEED NEW",
				img: Images1 + '/SOYAPRIMEGREEN.png',
				qtdPallet: 45,
				stockUn: "Qtd",
				family: "SEEDPRIME",
				showRecomendation: false,
				recomendation: {
					quantity : 10,
					unitPrice:  8.76
				},
				center: [
					{
						show: true,
						name: "SORRISO",
						stock: 45,
						listPrice: 34,
						taxPrice : 12.12,
						jurosPrice : 10,
						campaignPrice : 10,
						showLastBuy: true,
						showCart: false,
						lastBuy: "22/06/2022",
						leadTime: 5,
						quantity: 0,
						discount: 0,
						totalPrice: 0
					}
				]
			},
			{
				show: true,
				productCode: "0000010",
				name: "SOYAPRIME GREEN",
				img: Images1 + '/SOYAPRIMEGREEN.png',
				qtdPallet: 12,
				stockUn: "Qtd",
				family: "SEEDPRIME",
				showRecomendation: false,
				recomendation: {
					quantity : 10,
					unitPrice:  8.76
				},
				center: [
					{
						show: true,
						name: "SORRISO",
						stock: 12,
						listPrice: 54.42,
						taxPrice : 10,
						jurosPrice : 10,
						campaignPrice : 10,
						showLastBuy: true,
						showCart: false,
						lastBuy: "22/06/2022",
						leadTime: 5,
						quantity: 0,
						discount: 0,
						totalPrice: 0
					}
				]
			},
		];
}
const venezaData = () =>  {
	return [
			{
				show: true,
				productCode: "1007071",
				name: "Bebida Láctea Ameixa 150g",
				img: Images + '/venezaProduto1.png',
				stockUn: "UN",
				qtdPallet: 0,
				family: "BEBIDA",
				showRecomendation: true,
				recomendation: {
					quantity : 10,
					unitPrice:  8.76
				},
				center: [
					{
						show: true,
						name: "SAO PAULO",
						stock: 100,
						listPrice: 8.76,
						taxPrice : 1,
						jurosPrice : 1.20,
						campaignPrice : 0,
						showLastBuy: true,
						showCart: false,
						lastBuy: "10/05/2022",
						leadTime: 5,
						quantity: 0,
						discount: 0,
						totalPrice: 0
					},
					{
						show: true,
						name: "SAO CAETANO DO SUL",
						stock: 120,
						listPrice: 9.76,
						taxPrice : 1.5,
						jurosPrice : 1.70,
						campaignPrice : 0,
						showLastBuy: true,
						showCart: false,
						lastBuy: "10/05/2022",
						leadTime: 5,
						quantity: 0,
						discount: 0,
						totalPrice: 0
					},
				]
			},
			{
				show: true,
				productCode: "99147",
				name: "Bebida Láctea Morango 150g",
				img: Images + '/venezaProduto2.png',
				qtdPallet: 0,
				stockUn: "UN",
				family: "BEBIDA",
				showRecomendation: true,
				recomendation: {
					quantity : 10,
					unitPrice:  8.76
				},
				center: [
					{
						show: true,
						name: "SAO BERNARDO DO CAMPO",
						stockLabel: '10 Unidades',
						stock: 10,
						listPrice: 13.52,
						taxPrice : 0.7,
						jurosPrice : 1.20,
						campaignPrice : 0,
						showLastBuy: false,
						showCart: false,
						lastBuy: "10/05/2022",
						leadTime: 5,
						quantity: 0,
						discount: 0,
						totalPrice: 0
					},
					{
						show: true,
						name: "SAO CAETANO DO SUL",
						stockLabel: '200 Unidades',
						stock: 200,
						listPrice: 14.52,
						taxPrice : 1.5,
						jurosPrice : 1.70,
						campaignPrice : 0,
						showLastBuy: true,
						showCart: false,
						lastBuy: "11/05/2022",
						leadTime: 5,
						quantity: 0,
						discount: 0,
						totalPrice: 0
					}
				]
			},
			{
				show: true,
				productCode: "1008433",
				name: "Iogurte Ameixa 170g",
				img: Images + '/venezaProduto3.png',
				qtdPallet: 0,
				stockUn: "UN",
				family: "BEBIDA",
				showRecomendation: true,
				recomendation: {
					quantity : 10,
					unitPrice:  8.76
				},
				center: [
					{
						show: true,
						name: "SAO BERNARDO DO CAMPO",
						stockLabel: '90 Unidades',
						stock: 90,
						listPrice: 4.68,
						taxPrice : 0.1,
						jurosPrice : 0.12,
						campaignPrice : 0,
						showLastBuy: false,
						showCart: false,
						lastBuy: "10/05/2022",
						leadTime: 5,
						quantity: 0,
						discount: 0,
						totalPrice: 0
					},
					{
						show: true,
						name: "SAO CAETANO DO SUL",
						stockLabel: '232 Unidades',
						stock: 232,
						listPrice: 4.98,
						taxPrice : 0.4,
						jurosPrice : 0.12,
						campaignPrice : 0,
						showLastBuy: true,
						showCart: false,
						lastBuy: "11/05/2022",
						leadTime: 5,
						quantity: 0,
						discount: 0,
						totalPrice: 0
					}
				]
			},
			{
				show: true,
				productCode: "99121",
				name: "Creme de Ricota Light",
				img: Images + '/venezaProduto4.png',
				qtdPallet: 0,
				stockUn: "UN",
				family: "LINHA CREMOSA",
				showRecomendation: false,
				center: [
					{
						show: true,
						name: "SAO BERNARDO DO CAMPO",
						stockLabel: '10 Unidades',
						stock: 10,
						listPrice: 13.52,
						taxPrice : 0.7,
						jurosPrice : 1.20,
						campaignPrice : 0,
						showLastBuy: false,
						showCart: false,
						lastBuy: "10/05/2022",
						leadTime: 5,
						quantity: 0,
						discount: 0,
						totalPrice: 0
					},
					{
						show: true,
						name: "SAO CAETANO DO SUL",
						stockLabel: '200 Unidades',
						stock: 200,
						listPrice: 14.52,
						taxPrice : 1.5,
						jurosPrice : 1.70,
						campaignPrice : 0,
						showLastBuy: true,
						showCart: false,
						lastBuy: "11/05/2022",
						leadTime: 5,
						quantity: 0,
						discount: 0,
						totalPrice: 0
					}
				]
			},
			{
				show: true,
				productCode: "1008431",
				name: "Creme de Ricota Tradicional",
				img: Images + '/venezaProduto5.png',
				qtdPallet: 0,
				stockUn: "UN",
				family: "LINHA CREMOSA",
				showRecomendation: false,
				center: [
					{
						show: true,
						name: "SAO BERNARDO DO CAMPO",
						stockLabel: '90 Unidades',
						stock: 90,
						listPrice: 4.68,
						taxPrice : 0.1,
						jurosPrice : 0.12,
						campaignPrice : 0,
						showLastBuy: false,
						showCart: false,
						lastBuy: "10/05/2022",
						leadTime: 5,
						quantity: 0,
						discount: 0,
						totalPrice: 0
					},
					{
						show: true,
						name: "SAO CAETANO DO SUL",
						stockLabel: '232 Unidades',
						stock: 232,
						listPrice: 4.98,
						taxPrice : 0.4,
						jurosPrice : 0.12,
						campaignPrice : 0,
						showLastBuy: true,
						showCart: false,
						lastBuy: "11/05/2022",
						leadTime: 5,
						quantity: 0,
						discount: 0,
						totalPrice: 0
					}
				]
			},
			{
				show: true,
				productCode: "99142",
				name: "Queijo Coalho",
				img: Images + '/venezaProduto6.png',
				qtdPallet: 0,
				stockUn: "UN",
				family: "QUEIJOS",
				showRecomendation: false,
				center: [
					{
						show: true,
						name: "SAO BERNARDO DO CAMPO",
						stockLabel: '10 Unidades',
						stock: 10,
						listPrice: 13.52,
						taxPrice : 0.7,
						jurosPrice : 1.20,
						campaignPrice : 0,
						showLastBuy: false,
						showCart: false,
						lastBuy: "10/05/2022",
						leadTime: 5,
						quantity: 0,
						discount: 0,
						totalPrice: 0
					},
					{
						show: true,
						name: "SAO CAETANO DO SUL",
						stockLabel: '200 Unidades',
						stock: 200,
						listPrice: 14.52,
						taxPrice : 1.5,
						jurosPrice : 1.70,
						campaignPrice : 0,
						showLastBuy: true,
						showCart: false,
						lastBuy: "11/05/2022",
						leadTime: 5,
						quantity: 0,
						discount: 0,
						totalPrice: 0
					}
				]
			},
			{
				show: true,
				productCode: "1008491",
				name: "Queijo Condimentado com Orégano",
				img: Images + '/venezaProduto7.png',
				qtdPallet: 0,
				stockUn: "UN",
				family: "QUEIJOS",
				showRecomendation: false,
				center: [
					{
						show: true,
						name: "SAO BERNARDO DO CAMPO",
						stockLabel: '90 Unidades',
						stock: 90,
						listPrice: 4.68,
						taxPrice : 0.1,
						jurosPrice : 0.12,
						campaignPrice : 0,
						showLastBuy: false,
						showCart: false,
						lastBuy: "10/05/2022",
						leadTime: 5,
						quantity: 0,
						discount: 0,
						totalPrice: 0
					},
					{
						show: true,
						name: "SAO CAETANO DO SUL",
						stockLabel: '232 Unidades',
						stock: 232,
						listPrice: 4.98,
						taxPrice : 0.4,
						jurosPrice : 0.12,
						campaignPrice : 0,
						showLastBuy: true,
						showCart: false,
						lastBuy: "11/05/2022",
						leadTime: 5,
						quantity: 0,
						discount: 0,
						totalPrice: 0
					}
				]
			},
			{
				show: true,
				productCode: "1008492",
				name: "Queijo Condimentado com Pimenta Calabresa",
				img: Images + '/venezaProduto8.png',
				qtdPallet: 0,
				stockUn: "UN",
				family: "QUEIJOS",
				showRecomendation: false,
				center: [
					{
						show: true,
						name: "SAO BERNARDO DO CAMPO",
						stockLabel: '90 Unidades',
						stock: 90,
						listPrice: 4.68,
						taxPrice : 0.1,
						jurosPrice : 0.12,
						campaignPrice : 0,
						showLastBuy: false,
						showCart: false,
						lastBuy: "10/05/2022",
						leadTime: 5,
						quantity: 0,
						discount: 0,
						totalPrice: 0
					},
					{
						show: true,
						name: "SAO CAETANO DO SUL",
						stockLabel: '232 Unidades',
						stock: 232,
						listPrice: 4.98,
						taxPrice : 0.4,
						jurosPrice : 0.12,
						campaignPrice : 0,
						showLastBuy: true,
						showCart: false,
						lastBuy: "11/05/2022",
						leadTime: 5,
						quantity: 0,
						discount: 0,
						totalPrice: 0
					}
				]
			},
		];
}

const violeteraData = () =>  {
	return [
			{
				show: true,
				productCode: "1007071",
				name: "Azeitona Recheada com Presunto Ibérico La Violetera 130g",
				img: Images + '/azeitona-recheada-com-presunto-la-violetera-130g.jpg.webp',
				stockUn: "UN",
				qtdPallet: 0,
				family: "POTE",
				center: [
					{
						show: true,
						name: "SAO BERNARDO DO CAMPO",
						stockLabel: '100 Unidades',
						stock: 100,
						listPrice: 8.76,
						taxPrice : 1,
						jurosPrice : 1.20,
						campaignPrice : 0,
						showLastBuy: true,
						showCart: false,
						lastBuy: "10/05/2022",
						leadTime: 5,
						quantity: 0,
						discount: 0,
						totalPrice: 0
					},
					{
						show: true,
						name: "SAO CAETANO DO SUL",
						stockLabel: '110 Unidades',
						stock: 120,
						listPrice: 9.76,
						taxPrice : 1.5,
						jurosPrice : 1.70,
						campaignPrice : 0,
						showLastBuy: true,
						showCart: false,
						lastBuy: "10/05/2022",
						leadTime: 5,
						quantity: 0,
						discount: 0,
						totalPrice: 0
					},
				]
			},
			{
				show: true,
				productCode: "99147",
				name: "Azeitona Verde com caroço La Violetera 500g",
				img: Images + '/azeitona-verde-com-caroco-la-violetera-500g.jpg.webp',
				qtdPallet: 0,
				stockUn: "UN",
				family: "POTE",
				center: [
					{
						show: true,
						name: "SAO BERNARDO DO CAMPO",
						stockLabel: '10 Unidades',
						stock: 10,
						listPrice: 13.52,
						taxPrice : 0.7,
						jurosPrice : 1.20,
						campaignPrice : 0,
						showLastBuy: false,
						showCart: false,
						lastBuy: "10/05/2022",
						leadTime: 5,
						quantity: 0,
						discount: 0,
						totalPrice: 0
					},
					{
						show: true,
						name: "SAO CAETANO DO SUL",
						stockLabel: '200 Unidades',
						stock: 200,
						listPrice: 14.52,
						taxPrice : 1.5,
						jurosPrice : 1.70,
						campaignPrice : 0,
						showLastBuy: true,
						showCart: false,
						lastBuy: "11/05/2022",
						leadTime: 5,
						quantity: 0,
						discount: 0,
						totalPrice: 0
					}
				]
			},
			{
				show: true,
				productCode: "1008493",
				name: "Azeitona Preta Sem Caroço La Violetera Refil Doy Pack 120g",
				img: Images + '/azeitona-preta-sem-caroco-la-violetera-refil-doy-pack-120-gr.jpg.webp',
				qtdPallet: 0,
				stockUn: "UN",
				family: "REFIL",
				center: [
					{
						show: true,
						name: "SAO BERNARDO DO CAMPO",
						stockLabel: '90 Unidades',
						stock: 90,
						listPrice: 4.68,
						taxPrice : 0.1,
						jurosPrice : 0.12,
						campaignPrice : 0,
						showLastBuy: false,
						showCart: false,
						lastBuy: "10/05/2022",
						leadTime: 5,
						quantity: 0,
						discount: 0,
						totalPrice: 0
					},
					{
						show: true,
						name: "SAO CAETANO DO SUL",
						stockLabel: '232 Unidades',
						stock: 232,
						listPrice: 4.98,
						taxPrice : 0.4,
						jurosPrice : 0.12,
						campaignPrice : 0,
						showLastBuy: true,
						showCart: false,
						lastBuy: "11/05/2022",
						leadTime: 5,
						quantity: 0,
						discount: 0,
						totalPrice: 0
					}
				]
			},
		];
}

const iharaRecommendationData = (data) =>  {
	var returnData =  [];
	data.forEach(function(item){
		item.center.forEach(function(itemCenter){
			returnData.push(
        	{
        	    showCart : true,
        	    key: 'Areia de Fundição, Lamas Contaminadas - Regional LESTE',
        	    name: 'Areia de Fundição, Lamas Contaminadas',
        	    family: 'SOLIDOS',
        	    culture: 'Custo retirada: R$ 1.000',
        	    img: Images + '/produto2.png',
        	    salesTeam: 'Regional LESTE',
        	    order: '00011259 - KAIQUE CIRTO',
        	    date: '28/05/2022',
        	    margin: 20,
        	    quantity: 15,
        	    price: 90 
        	});
		});
	});
}

const itajaData = () =>  {
	return [
			{
				show: true,
				productCode: "0000010",
				name: "Desinfetante Hospitalar 70°",
				img: Images1 + '/alcool70.jpeg',
				stockUn: "Un",
				qtdPallet: 120,
				family: "Saneantes",
				showRecomendation: true,
				recomendation: {
					quantity : 10,
					unitPrice:  7.69
				},
				center: [
					{
						show: true,
						name: "São Paulo",
						stockLabel: '120 Qtd',
						stock: 120,
						listPrice: 7.5,
						taxPrice : 2,
						jurosPrice : 2.12,
						campaignPrice : 3,
						showLastBuy: true,
						showCart: false,
						lastBuy: "10/05/2022",
						leadTime: 5,
						quantity: 0,
						discount: 0,
						totalPrice: 0
					},
					{
						show: true,
						name: "Rio de Janeiro",
						stockLabel: '120 Qtd',
						stock: 120,
						listPrice: 7.5,
						taxPrice : 2,
						jurosPrice : 2.12,
						campaignPrice : 3,
						showLastBuy: true,
						showCart: false,
						lastBuy: "10/05/2022",
						leadTime: 5,
						quantity: 0,
						discount: 0,
						totalPrice: 0
					},
				]
			},
			{
				show: true,
				productCode: "0000020",
				name: "Álcool Líquido 46°",
				img: Images1 + '/alcoolliquido.jpg',
				stockUn: "Un",
				qtdPallet: 240,
				family: "Saneantes",
				showRecomendation: true,
				recomendation: {
					quantity : 14,
					unitPrice:  5
				},
				center: [
					{
						show: true,
						name: "Minas Gerais",
						stock: 60,
						listPrice: 4.96,
						taxPrice : 1,
						jurosPrice : 1.5,
						campaignPrice : 4,
						showLastBuy: true,
						showCart: false,
						lastBuy: "22/06/2022",
						leadTime: 5,
						quantity: 0,
						discount: 0,
						totalPrice: 0
					},
					{
						show: true,
						name: "Rio de Janeiro",
						stock: 60,
						listPrice: 4.84,
						taxPrice : 1,
						jurosPrice : 1.5,
						campaignPrice : 4,
						showLastBuy: true,
						showCart: false,
						lastBuy: "22/06/2022",
						leadTime: 5,
						quantity: 0,
						discount: 0,
						totalPrice: 0
					},
				]
			},
			{
				show: true,
				productCode: "0000030",
				name: "Açucar Cristal Itaja 1Kg",
				img: Images1 + '/itajacucar.png',
				qtdPallet: 45,
				stockUn: "2 Kg",
				family: "Açucar",
				showRecomendation: false,
				recomendation: {
					quantity : 20,
					unitPrice:  4
				},
				center: [
					{
						show: true,
						name: "Minas Gerais",
						stock: 60,
						listPrice: 4.96,
						taxPrice : 1,
						jurosPrice : 1.5,
						campaignPrice : 4,
						showLastBuy: true,
						showCart: false,
						lastBuy: "22/06/2022",
						leadTime: 5,
						quantity: 0,
						discount: 0,
						totalPrice: 0
					},
					{
						show: true,
						name: "Rio de Janeiro",
						stock: 60,
						listPrice: 4.84,
						taxPrice : 1,
						jurosPrice : 1.5,
						campaignPrice : 4,
						showLastBuy: true,
						showCart: false,
						lastBuy: "22/06/2022",
						leadTime: 5,
						quantity: 0,
						discount: 0,
						totalPrice: 0
					},
				]
			},
			{
				show: true,
				productCode: "0000030",
				name: "Açucar Orgânico Itaja 1Kg",
				img: Images1 + '/acucarorganico2.jpeg',
				qtdPallet: 45,
				stockUn: "500 g",
				family: "Açúcar",
				showRecomendation: false,
				recomendation: {
					quantity : 20,
					unitPrice:  6
				},
				center: [
					{
						show: true,
						name: "Minas Gerais",
						stock: 60,
						listPrice: 6.96,
						taxPrice : 1,
						jurosPrice : 1.5,
						campaignPrice : 4,
						showLastBuy: true,
						showCart: false,
						lastBuy: "22/06/2022",
						leadTime: 5,
						quantity: 0,
						discount: 0,
						totalPrice: 0
					},
					{
						show: true,
						name: "Rio de Janeiro",
						stock: 60,
						listPrice: 7.84,
						taxPrice : 1,
						jurosPrice : 1.5,
						campaignPrice : 4,
						showLastBuy: true,
						showCart: false,
						lastBuy: "22/06/2022",
						leadTime: 5,
						quantity: 0,
						discount: 0,
						totalPrice: 0
					},
				]
			},
		];
}
const unitFertData = () =>  {
	return [
			{
				show: true,
				productCode: "0000010",
				name: "UNI 5KG",
				img: Images1 + '/univermelho-menor-350x430.jpg',
				stockUn: "Un",
				qtdPallet: 120,
				family: "FERTILIZANTES",
				showRecomendation: true,
				recomendation: {
					quantity : 10,
					unitPrice:  7.69
				},
				center: [
					{
						show: true,
						name: "MILHO",
						stockLabel: '120 Qtd',
						stock: 120,
						listPrice: 7.5,
						taxPrice : 2,
						jurosPrice : 2.12,
						campaignPrice : 3,
						showLastBuy: true,
						showCart: false,
						lastBuy: "10/05/2022",
						leadTime: 5,
						quantity: 0,
						discount: 0,
						totalPrice: 0
					},
					{
						show: true,
						name: "SOJA",
						stockLabel: '120 Qtd',
						stock: 120,
						listPrice: 7.5,
						taxPrice : 2,
						jurosPrice : 2.12,
						campaignPrice : 3,
						showLastBuy: true,
						showCart: false,
						lastBuy: "10/05/2022",
						leadTime: 5,
						quantity: 0,
						discount: 0,
						totalPrice: 0
					},
				]
			},
			{
				show: true,
				productCode: "0000020",
				name: "PREMIUM 5KG",
				img: Images1 + '/premium-332x430.jpg',
				stockUn: "Un",
				qtdPallet: 240,
				family: "NUTRICIONAL",
				showRecomendation: true,
				recomendation: {
					quantity : 14,
					unitPrice:  5
				},
				center: [
					{
						show: true,
						name: "MILHO",
						stockLabel: '120 Qtd',
						stock: 120,
						listPrice: 7.5,
						taxPrice : 2,
						jurosPrice : 2.12,
						campaignPrice : 3,
						showLastBuy: true,
						showCart: false,
						lastBuy: "10/05/2022",
						leadTime: 5,
						quantity: 0,
						discount: 0,
						totalPrice: 0
					},
					{
						show: true,
						name: "SOJA",
						stockLabel: '120 Qtd',
						stock: 120,
						listPrice: 7.5,
						taxPrice : 2,
						jurosPrice : 2.12,
						campaignPrice : 3,
						showLastBuy: true,
						showCart: false,
						lastBuy: "10/05/2022",
						leadTime: 5,
						quantity: 0,
						discount: 0,
						totalPrice: 0
					},
				]
			},
			{
				show: true,
				productCode: "0000030",
				name: "PREMIUM MAX 5KG",
				img: Images1 + '/premium-max-menor-350x430.jpg',
				qtdPallet: 45,
				stockUn: "Kg",
				family: "NUTRICIONAL",
				showRecomendation: false,
				recomendation: {
					quantity : 20,
					unitPrice:  4
				},
				center: [
					{
						show: true,
						name: "MILHO",
						stockLabel: '120 Qtd',
						stock: 120,
						listPrice: 7.5,
						taxPrice : 2,
						jurosPrice : 2.12,
						campaignPrice : 3,
						showLastBuy: true,
						showCart: false,
						lastBuy: "10/05/2022",
						leadTime: 5,
						quantity: 0,
						discount: 0,
						totalPrice: 0
					},
					{
						show: true,
						name: "SOJA",
						stockLabel: '120 Qtd',
						stock: 120,
						listPrice: 7.5,
						taxPrice : 2,
						jurosPrice : 2.12,
						campaignPrice : 3,
						showLastBuy: true,
						showCart: false,
						lastBuy: "10/05/2022",
						leadTime: 5,
						quantity: 0,
						discount: 0,
						totalPrice: 0
					},
				]
			},
			{
				show: true,
				productCode: "0000030",
				name: "N MAX 2KG",
				img: Images1 + '/nmax-menor-350x430.jpg',
				qtdPallet: 45,
				stockUn: "2Kg ",
				family: "FERTILIZANTES",
				showRecomendation: false,
				recomendation: {
					quantity : 20,
					unitPrice:  6
				},
				center: [
					{
						show: true,
						name: "MILHO",
						stockLabel: '120 Qtd',
						stock: 120,
						listPrice: 7.5,
						taxPrice : 2,
						jurosPrice : 2.12,
						campaignPrice : 3,
						showLastBuy: true,
						showCart: false,
						lastBuy: "10/05/2022",
						leadTime: 5,
						quantity: 0,
						discount: 0,
						totalPrice: 0
					},
					{
						show: true,
						name: "SOJA",
						stockLabel: '120 Qtd',
						stock: 120,
						listPrice: 7.5,
						taxPrice : 2,
						jurosPrice : 2.12,
						campaignPrice : 3,
						showLastBuy: true,
						showCart: false,
						lastBuy: "10/05/2022",
						leadTime: 5,
						quantity: 0,
						discount: 0,
						totalPrice: 0
					},
				]
			},
			{
				show: true,
				productCode: "0000030",
				name: "FULL 2KG",
				img: Images1 + '/FULL-MENOR-350x430.jpg',
				qtdPallet: 45,
				stockUn: "2Kg ",
				family: "FERTILIZANTES NITROGENADOS",
				showRecomendation: false,
				recomendation: {
					quantity : 20,
					unitPrice:  6
				},
				center: [
					{
						show: true,
						name: "MILHO",
						stockLabel: '120 Qtd',
						stock: 120,
						listPrice: 7.5,
						taxPrice : 2,
						jurosPrice : 2.12,
						campaignPrice : 3,
						showLastBuy: true,
						showCart: false,
						lastBuy: "10/05/2022",
						leadTime: 5,
						quantity: 0,
						discount: 0,
						totalPrice: 0
					},
					{
						show: true,
						name: "SOJA",
						stockLabel: '120 Qtd',
						stock: 120,
						listPrice: 7.5,
						taxPrice : 2,
						jurosPrice : 2.12,
						campaignPrice : 3,
						showLastBuy: true,
						showCart: false,
						lastBuy: "10/05/2022",
						leadTime: 5,
						quantity: 0,
						discount: 0,
						totalPrice: 0
					},
				]
			},
			{
				show: true,
				productCode: "0000030",
				name: "FULL NMAX 5KG",
				img: Images1 + '/nmax-menor-350x430 (1).jpg',
				qtdPallet: 45,
				stockUn: "2Kg ",
				family: "FERTILIZANTES NITROGENADOS",
				showRecomendation: true,
				recomendation: {
					quantity : 20,
					unitPrice:  6
				},
				center: [
					{
						show: true,
						name: "MILHO",
						stockLabel: '120 Qtd',
						stock: 120,
						listPrice: 7.5,
						taxPrice : 2,
						jurosPrice : 2.12,
						campaignPrice : 3,
						showLastBuy: true,
						showCart: false,
						lastBuy: "10/05/2022",
						leadTime: 5,
						quantity: 0,
						discount: 0,
						totalPrice: 0
					},
					{
						show: true,
						name: "SOJA",
						stockLabel: '120 Qtd',
						stock: 120,
						listPrice: 7.5,
						taxPrice : 2,
						jurosPrice : 2.12,
						campaignPrice : 3,
						showLastBuy: true,
						showCart: false,
						lastBuy: "10/05/2022",
						leadTime: 5,
						quantity: 0,
						discount: 0,
						totalPrice: 0
					},
				]
			},
			{
				show: true,
				productCode: "0000030",
				name: "UNICAL 5KG",
				img: Images1 + '/Unical-juntos-menor.jpg',
				qtdPallet: 45,
				stockUn: "2Kg ",
				family: "NUTRICIONAL",
				showRecomendation: false,
				recomendation: {
					quantity : 20,
					unitPrice:  6
				},
				center: [
					{
						show: true,
						name: "MILHO",
						stockLabel: '120 Qtd',
						stock: 120,
						listPrice: 7.5,
						taxPrice : 2,
						jurosPrice : 2.12,
						campaignPrice : 3,
						showLastBuy: true,
						showCart: false,
						lastBuy: "10/05/2022",
						leadTime: 5,
						quantity: 0,
						discount: 0,
						totalPrice: 0
					},
					{
						show: true,
						name: "SOJA",
						stockLabel: '120 Qtd',
						stock: 120,
						listPrice: 7.5,
						taxPrice : 2,
						jurosPrice : 2.12,
						campaignPrice : 3,
						showLastBuy: true,
						showCart: false,
						lastBuy: "10/05/2022",
						leadTime: 5,
						quantity: 0,
						discount: 0,
						totalPrice: 0
					},
				]
			},
		];
}

const javData = () =>  {
	return [
			{
				show: true,
				productCode: "0000010",
				name: "Robôs de 6 Eixos C4 (Compactos)",
				img: Images1 + '/6-EIXOS_C4_ImagenBig.png',
				stockUn: "Un",
				qtdPallet: 1,
				family: "ROBOS",
				showRecomendation: true,
				recomendation: {
					quantity : 1,
					unitPrice:  1237.69
				},
				center: [
					{
						show: true,
						name: "SAO PAULO",
						stockLabel: '1 Qtd',
						stock: 1,
						listPrice: 1237.5,
						taxPrice : 212,
						jurosPrice : 322.12,
						campaignPrice : 1233,
						showLastBuy: true,
						showCart: false,
						lastBuy: "10/05/2022",
						leadTime: 5,
						quantity: 0,
						discount: 0,
						totalPrice: 0,
						showReposition: true,
						reposition:{
                			culture: 'Quantidade disponivel no pedido: 1 de 1',
                			order: '00011259 - KAIQUE CIRTO',
                			date: '28/05/2022',
                			margin: 20,
                			quantity: 1,
                			price: 1237.5
						},
					},
					{
						show: true,
						name: "RIO DE JANEIRO",
						stockLabel: '2 Qtd',
						stock: 2,
						listPrice: 1237.5,
						taxPrice : 212,
						jurosPrice : 322.12,
						campaignPrice : 1233,
						showLastBuy: true,
						showCart: false,
						lastBuy: "10/05/2022",
						leadTime: 5,
						quantity: 0,
						discount: 0,
						totalPrice: 0
					},
				]
			},
			{
				show: true,
				productCode: "0000020",
				name: "Controlador RC700A",
				img: Images1 + '/rc700a_000_690x460.jpg',
				stockUn: "Un",
				qtdPallet: 23,
				family: "CONTROLADOR",
				showRecomendation: true,
				recomendation: {
					quantity : 3,
					unitPrice:  341
				},
				center: [
					{
						show: true,
						name: "MINAS GERAIS",
						stockLabel: '12 Qtd',
						stock: 12,
						listPrice: 351,
						taxPrice : 34,
						jurosPrice : 21.12,
						campaignPrice : 340,
						showLastBuy: true,
						showCart: false,
						lastBuy: "10/05/2022",
						leadTime: 5,
						quantity: 0,
						discount: 0,
						totalPrice: 0,
						showReposition: true,
						reposition:{
                			culture: 'Quantidade disponivel no pedido: 1 de 1',
                			order: '00011260 - KAIQUE CIRTO',
                			date: '31/05/2022',
                			margin: 20,
                			quantity: 1,
                			price: 314.5
						},
					},
					{
						show: true,
						name: "MATO GROSSO DO SUL",
						stockLabel: '9 Qtd',
						stock: 9,
						listPrice: 351,
						taxPrice : 34,
						jurosPrice : 21.12,
						campaignPrice : 340,
						showLastBuy: true,
						showCart: false,
						lastBuy: "10/05/2022",
						leadTime: 5,
						quantity: 0,
						discount: 0,
						totalPrice: 0
					},
				]
			},
			{
				show: true,
				productCode: "0000020",
				name: "Robôs Mini SCARA Epson G1 - 225 mm",
				img: Images1 + '/g1_000_690x460.jpg',
				stockUn: "Un",
				qtdPallet: 43,
				family: "CONTROLADOR",
				showRecomendation: true,
				recomendation: {
					quantity : 12,
					unitPrice:  341
				},
				center: [
					{
						show: true,
						name: "MINAS GERAIS",
						stockLabel: '23 Qtd',
						stock: 12,
						listPrice: 351,
						taxPrice : 34,
						jurosPrice : 21.12,
						campaignPrice : 340,
						showLastBuy: true,
						showCart: false,
						lastBuy: "10/05/2022",
						leadTime: 5,
						quantity: 0,
						discount: 0,
						totalPrice: 0
					},
					{
						show: true,
						name: "MATO GROSSO DO SUL",
						stockLabel: '20 Qtd',
						stock: 9,
						listPrice: 351,
						taxPrice : 34,
						jurosPrice : 21.12,
						campaignPrice : 340,
						showLastBuy: true,
						showCart: false,
						lastBuy: "10/05/2022",
						leadTime: 5,
						quantity: 0,
						discount: 0,
						totalPrice: 0
					},
				]
			},
			{
				show: true,
				productCode: "0000020",
				name: "Robôs Epson SCARA G3 - 300 mm",
				img: Images1 + '/g3_000_690x460.jpg',
				stockUn: "Un",
				qtdPallet: 21,
				family: "CONTROLADOR",
				showRecomendation: true,
				recomendation: {
					quantity : 12,
					unitPrice:  341
				},
				center: [
					{
						show: true,
						name: "SAO PAULO",
						stockLabel: '23 Qtd',
						stock: 12,
						listPrice: 351,
						taxPrice : 34,
						jurosPrice : 21.12,
						campaignPrice : 340,
						showLastBuy: true,
						showCart: false,
						lastBuy: "10/05/2022",
						leadTime: 5,
						quantity: 0,
						discount: 0,
						totalPrice: 0
					},
					{
						show: true,
						name: "MATO GROSSO DO SUL",
						stockLabel: '20 Qtd',
						stock: 9,
						listPrice: 351,
						taxPrice : 34,
						jurosPrice : 21.12,
						campaignPrice : 340,
						showLastBuy: true,
						showCart: false,
						lastBuy: "10/05/2022",
						leadTime: 5,
						quantity: 0,
						discount: 0,
						totalPrice: 0
					},
				]
			}
		];
}
const vittiaData = () =>  {
	return [
			{
				show: true,
				productCode: "0000010",
				name: "Meli-X Turbo 100L",
				img: Images1 + '/vittia1.jpeg',
				stockUn: "Un",
				qtdPallet: 1,
				family: "Inoculantes",
				showRecomendation: true,
				recomendation: {
					quantity : 1,
					unitPrice:  1237.69
				},
				center: [
					{
						show: true,
						name: "SOJA",
						stockLabel: '1 Qtd',
						stock: 1,
						listPrice: 1237.5,
						taxPrice : 212,
						jurosPrice : 322.12,
						campaignPrice : 1233,
						showLastBuy: true,
						showCart: false,
						lastBuy: "10/05/2022",
						leadTime: 5,
						quantity: 0,
						discount: 0,
						totalPrice: 0,
						showReposition: true,
						reposition:{
                			culture: 'Quantidade disponivel no pedido: 1 de 1',
                			order: '00011259 - KAIQUE CIRTO',
                			date: '28/05/2022',
                			margin: 20,
                			quantity: 1,
                			price: 1237.5
						},
					},
					{
						show: true,
						name: "CAFE",
						stockLabel: '2 Qtd',
						stock: 2,
						listPrice: 1237.5,
						taxPrice : 212,
						jurosPrice : 322.12,
						campaignPrice : 1233,
						showLastBuy: true,
						showCart: false,
						lastBuy: "10/05/2022",
						leadTime: 5,
						quantity: 0,
						discount: 0,
						totalPrice: 0
					},
				]
			},
			{
				show: true,
				productCode: "0000020",
				name: "Bio-Imune 10 KG",
				img: Images1 + '/bio-imune-01.jpg',
				stockUn: "Un",
				qtdPallet: 23,
				family: "Microbiológicos",
				showRecomendation: true,
				recomendation: {
					quantity : 3,
					unitPrice:  341
				},
				center: [
					{
						show: true,
						name: "ALGODÃO",
						stockLabel: '12 Qtd',
						stock: 12,
						listPrice: 351,
						taxPrice : 34,
						jurosPrice : 21.12,
						campaignPrice : 340,
						showLastBuy: true,
						showCart: false,
						lastBuy: "10/05/2022",
						leadTime: 5,
						quantity: 0,
						discount: 0,
						totalPrice: 0,
						showReposition: true,
						reposition:{
                			culture: 'Quantidade disponivel no pedido: 1 de 1',
                			order: '00011260 - KAIQUE CIRTO',
                			date: '31/05/2022',
                			margin: 20,
                			quantity: 1,
                			price: 314.5
						},
					},
					{
						show: true,
						name: "MILHO",
						stockLabel: '9 Qtd',
						stock: 9,
						listPrice: 351,
						taxPrice : 34,
						jurosPrice : 21.12,
						campaignPrice : 340,
						showLastBuy: true,
						showCart: false,
						lastBuy: "10/05/2022",
						leadTime: 5,
						quantity: 0,
						discount: 0,
						totalPrice: 0
					},
				]
			},
			{
				show: true,
				productCode: "0000020",
				name: "Bioenergy 10L",
				img: Images1 + '/bioenergy-03.jpg',
				stockUn: "Un",
				qtdPallet: 43,
				family: "Biofertilizantes",
				showRecomendation: true,
				recomendation: {
					quantity : 12,
					unitPrice:  341
				},
				center: [
					{
						show: true,
						name: "ALGODÃO",
						stockLabel: '23 Qtd',
						stock: 12,
						listPrice: 351,
						taxPrice : 34,
						jurosPrice : 21.12,
						campaignPrice : 340,
						showLastBuy: true,
						showCart: false,
						lastBuy: "10/05/2022",
						leadTime: 5,
						quantity: 0,
						discount: 0,
						totalPrice: 0
					},
					{
						show: true,
						name: "MILHO",
						stockLabel: '20 Qtd',
						stock: 9,
						listPrice: 351,
						taxPrice : 34,
						jurosPrice : 21.12,
						campaignPrice : 340,
						showLastBuy: true,
						showCart: false,
						lastBuy: "10/05/2022",
						leadTime: 5,
						quantity: 0,
						discount: 0,
						totalPrice: 0
					},
				]
			},
			{
				show: true,
				productCode: "0000020",
				name: "Nitroflex®",
				img: Images1 + '/nitroflex-02.jpg',
				stockUn: "Un",
				qtdPallet: 21,
				family: "Adjuvantes Comum",
				showRecomendation: true,
				recomendation: {
					quantity : 12,
					unitPrice:  341
				},
				center: [
					{
						show: true,
						name: "SOJA",
						stockLabel: '23 Qtd',
						stock: 12,
						listPrice: 351,
						taxPrice : 34,
						jurosPrice : 21.12,
						campaignPrice : 340,
						showLastBuy: true,
						showCart: false,
						lastBuy: "10/05/2022",
						leadTime: 5,
						quantity: 0,
						discount: 0,
						totalPrice: 0
					},
					{
						show: true,
						name: "MILHO",
						stockLabel: '20 Qtd',
						stock: 9,
						listPrice: 351,
						taxPrice : 34,
						jurosPrice : 21.12,
						campaignPrice : 340,
						showLastBuy: true,
						showCart: false,
						lastBuy: "10/05/2022",
						leadTime: 5,
						quantity: 0,
						discount: 0,
						totalPrice: 0
					},
				]
			}
		];
}
const plantaeData = () =>  {
	return [
			{
				show: true,
				productCode: "0000010",
				name: "MILHO",
				// img: Images1 + '/vittia1.jpeg',
				stockUn: "SACAS",
				qtdPallet: 10,
				family: "GRÃOS",
				showRecomendation: true,
				recomendation: {
					quantity : 1,
					unitPrice:  1237.69
				},
				center: [
					{
						show: true,
						name: "SAO PAULO",
						stockLabel: '1 Qtd',
						stock: 1,
						listPrice: 1237.5,
						taxPrice : 212,
						jurosPrice : 322.12,
						campaignPrice : 1233,
						showLastBuy: true,
						showCart: false,
						lastBuy: "10/05/2022",
						leadTime: 5,
						quantity: 0,
						discount: 0,
						totalPrice: 0,
						showReposition: true,
						reposition:{
                			culture: 'Quantidade disponivel no pedido: 1 de 1',
                			order: '00011259 - KAIQUE CIRTO',
                			date: '28/05/2022',
                			margin: 20,
                			quantity: 1,
                			price: 1237.5
						},
					},
					{
						show: true,
						name: "RIO DE JANEIRO",
						stockLabel: '2 Qtd',
						stock: 2,
						listPrice: 1237.5,
						taxPrice : 212,
						jurosPrice : 322.12,
						campaignPrice : 1233,
						showLastBuy: true,
						showCart: false,
						lastBuy: "10/05/2022",
						leadTime: 5,
						quantity: 0,
						discount: 0,
						totalPrice: 0
					},
				]
			},
			{
				show: true,
				productCode: "0000020",
				name: "SOJA",
				// img: Images1 + '/vittia1.jpeg',
				stockUn: "SACAS",
				qtdPallet: 10,
				family: "GRÃOS",
				showRecomendation: true,
				recomendation: {
					quantity : 1,
					unitPrice:  1237.69
				},
				center: [
					{
						show: true,
						name: "SAO PAULO",
						stockLabel: '1 Qtd',
						stock: 1,
						listPrice: 1237.5,
						taxPrice : 212,
						jurosPrice : 322.12,
						campaignPrice : 1233,
						showLastBuy: true,
						showCart: false,
						lastBuy: "10/05/2022",
						leadTime: 5,
						quantity: 0,
						discount: 0,
						totalPrice: 0,
						showReposition: true,
						reposition:{
                			culture: 'Quantidade disponivel no pedido: 1 de 1',
                			order: '00011259 - KAIQUE CIRTO',
                			date: '28/05/2022',
                			margin: 20,
                			quantity: 1,
                			price: 1237.5
						},
					},
					{
						show: true,
						name: "RIO DE JANEIRO",
						stockLabel: '2 Qtd',
						stock: 2,
						listPrice: 1237.5,
						taxPrice : 212,
						jurosPrice : 322.12,
						campaignPrice : 1233,
						showLastBuy: true,
						showCart: false,
						lastBuy: "10/05/2022",
						leadTime: 5,
						quantity: 0,
						discount: 0,
						totalPrice: 0
					},
				]
			},
			{
				show: true,
				productCode: "0000030",
				name: "GERMEM",
				// img: Images1 + '/vittia1.jpeg',
				stockUn: "SACAS",
				qtdPallet: 10,
				family: "PROCESSADOS",
				showRecomendation: true,
				recomendation: {
					quantity : 1,
					unitPrice:  1237.69
				},
				center: [
					{
						show: true,
						name: "SAO PAULO",
						stockLabel: '1 Qtd',
						stock: 1,
						listPrice: 1237.5,
						taxPrice : 212,
						jurosPrice : 322.12,
						campaignPrice : 1233,
						showLastBuy: true,
						showCart: false,
						lastBuy: "10/05/2022",
						leadTime: 5,
						quantity: 0,
						discount: 0,
						totalPrice: 0,
						showReposition: true,
						reposition:{
                			culture: 'Quantidade disponivel no pedido: 1 de 1',
                			order: '00011259 - KAIQUE CIRTO',
                			date: '28/05/2022',
                			margin: 20,
                			quantity: 1,
                			price: 1237.5
						},
					},
					{
						show: true,
						name: "RIO DE JANEIRO",
						stockLabel: '2 Qtd',
						stock: 2,
						listPrice: 1237.5,
						taxPrice : 212,
						jurosPrice : 322.12,
						campaignPrice : 1233,
						showLastBuy: true,
						showCart: false,
						lastBuy: "10/05/2022",
						leadTime: 5,
						quantity: 0,
						discount: 0,
						totalPrice: 0
					},
				]
			},
		];
}
const fertiSystemData = () =>  {
	return [
			{
				show: true,
				productCode: "110100",
				name: "Auto-Lub AP NG",
				img: Images1 + '/7_1_0_007_apngmancalesquerdo2.webp',
				stockUn: "QTD",
				qtdPallet: 10,
				family: "Dosador",
				showRecomendation: true,
				recomendation: {
					quantity : 1,
					unitPrice:  495.00
				},
				center: [
					{
						show: true,
						name: "SAO PAULO",
						stockLabel: '1 Qtd',
						stock: 1,
						listPrice: 405.00,
						taxPrice : 30,
						jurosPrice : 10,
						campaignPrice : 479,
						showLastBuy: true,
						showCart: false,
						lastBuy: "10/02/2023",
						leadTime: 5,
						quantity: 0,
						discount: 0,
						totalPrice: 0,
						showReposition: true,
						reposition:{
                			culture: 'Quantidade disponivel no pedido: 1 de 1',
                			order: '00011259 - KAIQUE CIRTO',
                			date: '28/05/2022',
                			margin: 20,
                			quantity: 1,
                			price: 498.5
						},
					},
					{
						show: true,
						name: "RIO DE JANEIRO",
						stockLabel: '2 Qtd',
						stock: 2,
						listPrice: 415.00,
						taxPrice : 35,
						jurosPrice : 10,
						campaignPrice : 479,
						showLastBuy: true,
						showCart: false,
						lastBuy: "10/05/2022",
						leadTime: 5,
						quantity: 0,
						discount: 0,
						totalPrice: 0
					},
				]
			},
			{
				show: true,
				productCode: "450451002",
				name: "ITS 5000",
				img: Images1 + '/16_11_4_487_its1.webp',
				stockUn: "ATD",
				qtdPallet: 10,
				family: "Dosador",
				showRecomendation: true,
				recomendation: {
					quantity : 1,
					unitPrice:  570
				},
				center: [
					{
						show: true,
						name: "SAO PAULO",
						stockLabel: '1 Qtd',
						stock: 1,
						listPrice: 540,
						taxPrice : 20,
						jurosPrice : 10,
						campaignPrice : 530,
						showLastBuy: true,
						showCart: false,
						lastBuy: "10/05/2022",
						leadTime: 5,
						quantity: 0,
						discount: 0,
						totalPrice: 0,
						showReposition: true,
						reposition:{
                			culture: 'Quantidade disponivel no pedido: 1 de 1',
                			order: '00011259 - KAIQUE CIRTO',
                			date: '28/05/2022',
                			margin: 20,
                			quantity: 1,
                			price: 1237.5
						},
					},
					{
						show: true,
						name: "RIO DE JANEIRO",
						stockLabel: '2 Qtd',
						stock: 2,
						listPrice: 540,
						taxPrice : 30,
						jurosPrice : 10,
						campaignPrice : 530,
						showLastBuy: true,
						showCart: false,
						lastBuy: "10/05/2022",
						leadTime: 5,
						quantity: 0,
						discount: 0,
						totalPrice: 0
					},
				]
			},
			{
				show: true,
				productCode: "104006",
				name: "FS Nível",
				img: Images1 + '/10_11_6_632_fsnvel2.webp',
				stockUn: "Qtd",
				qtdPallet: 10,
				family: "Equipamento Auxiliar",
				showRecomendation: true,
				recomendation: {
					quantity : 1,
					unitPrice:  1840
				},
				center: [
					{
						show: true,
						name: "SAO PAULO",
						stockLabel: '1 Qtd',
						stock: 1,
						listPrice: 1540,
						taxPrice : 200,
						jurosPrice : 100,
						campaignPrice : 1790,
						showLastBuy: true,
						showCart: false,
						lastBuy: "10/05/2022",
						leadTime: 5,
						quantity: 0,
						discount: 0,
						totalPrice: 0,
						showReposition: true,
						reposition:{
                			culture: 'Quantidade disponivel no pedido: 1 de 1',
                			order: '00011259 - KAIQUE CIRTO',
                			date: '28/05/2022',
                			margin: 20,
                			quantity: 1,
                			price: 1237.5
						},
					},
					{
						show: true,
						name: "RIO DE JANEIRO",
						stockLabel: '2 Qtd',
						stock: 2,
						listPrice: 1540,
						taxPrice : 200,
						jurosPrice : 100,
						campaignPrice : 1790,
						showLastBuy: true,
						showCart: false,
						lastBuy: "10/05/2022",
						leadTime: 5,
						quantity: 0,
						discount: 0,
						totalPrice: 0
					},
				]
			},
			{
				show: true,
				productCode: "303315004",
				name: "ETD",
				img: Images1 + '/15_11_2_210_ETD.webp',
				stockUn: "Qtd",
				qtdPallet: 7,
				family: "Tabela eletrônica",
				showRecomendation: true,
				recomendation: {
					quantity : 1,
					unitPrice: 2191.15
				},
				center: [
					{
						show: true,
						name: "SAO PAULO",
						stockLabel: '1 Qtd',
						stock: 1,
						listPrice: 2001.15,
						taxPrice : 100,
						jurosPrice : 50,
						campaignPrice : 2171.15,
						showLastBuy: true,
						showCart: false,
						lastBuy: "10/05/2022",
						leadTime: 5,
						quantity: 0,
						discount: 0,
						totalPrice: 0,
						showReposition: true,
						reposition:{
                			culture: 'Quantidade disponivel no pedido: 1 de 1',
                			order: '00011259 - KAIQUE CIRTO',
                			date: '28/05/2022',
                			margin: 20,
                			quantity: 1,
                			price: 1237.5
						},
					},
					{
						show: true,
						name: "RIO DE JANEIRO",
						stockLabel: '2 Qtd',
						stock: 2,
						listPrice: 2001.15,
						taxPrice : 100,
						jurosPrice : 50,
						campaignPrice : 2171.15,
						showLastBuy: true,
						showCart: false,
						lastBuy: "10/05/2022",
						leadTime: 5,
						quantity: 0,
						discount: 0,
						totalPrice: 0
					},
				]
			},
		];
}
const VeilingData = () =>  {
	return [
			{
				show: true,
				productCode: "110100",
				name: "ALOE ARISTATA COM GLITTER PLUS P11 COLOURS DECORADO",
				img: Images1 + '/aloe-arist-colours-dc-62b0e6df07a9e.jpeg',
				stockUn: "QTD",
				qtdPallet: 10,
				family: "DECORADO",
				showRecomendation: true,
				recomendation: {
					quantity : 1,
					unitPrice:  495.00
				},
				center: [
					{
						show: true,
						name: "SAO PAULO",
						stockLabel: '1 Qtd',
						stock: 1,
						listPrice: 405.00,
						taxPrice : 30,
						jurosPrice : 10,
						campaignPrice : 479,
						showLastBuy: true,
						showCart: false,
						lastBuy: "10/02/2023",
						leadTime: 5,
						quantity: 0,
						discount: 0,
						totalPrice: 0,
						showReposition: true,
						reposition:{
                			culture: 'Quantidade disponivel no pedido: 1 de 1',
                			order: '00011259 - KAIQUE CIRTO',
                			date: '28/05/2022',
                			margin: 20,
                			quantity: 1,
                			price: 498.5
						},
					},
					{
						show: true,
						name: "RIO DE JANEIRO",
						stockLabel: '2 Qtd',
						stock: 2,
						listPrice: 415.00,
						taxPrice : 35,
						jurosPrice : 10,
						campaignPrice : 479,
						showLastBuy: true,
						showCart: false,
						lastBuy: "10/05/2022",
						leadTime: 5,
						quantity: 0,
						discount: 0,
						totalPrice: 0
					},
				]
			},
			{
				show: true,
				productCode: "450451002",
				name: "AGAPANTHUS AZUL",
				img: Images1 + '/agapanthus-az-62b1b777f41fc-300x225.jpeg',
				stockUn: "ATD",
				qtdPallet: 10,
				family: "FLOR DE CORTE",
				showRecomendation: true,
				recomendation: {
					quantity : 1,
					unitPrice:  570
				},
				center: [
					{
						show: true,
						name: "SAO PAULO",
						stockLabel: '1 Qtd',
						stock: 1,
						listPrice: 540,
						taxPrice : 20,
						jurosPrice : 10,
						campaignPrice : 530,
						showLastBuy: true,
						showCart: false,
						lastBuy: "10/05/2022",
						leadTime: 5,
						quantity: 0,
						discount: 0,
						totalPrice: 0,
						showReposition: true,
						reposition:{
                			culture: 'Quantidade disponivel no pedido: 1 de 1',
                			order: '00011259 - KAIQUE CIRTO',
                			date: '28/05/2022',
                			margin: 20,
                			quantity: 1,
                			price: 1237.5
						},
					},
					{
						show: true,
						name: "RIO DE JANEIRO",
						stockLabel: '2 Qtd',
						stock: 2,
						listPrice: 540,
						taxPrice : 30,
						jurosPrice : 10,
						campaignPrice : 530,
						showLastBuy: true,
						showCart: false,
						lastBuy: "10/05/2022",
						leadTime: 5,
						quantity: 0,
						discount: 0,
						totalPrice: 0
					},
				]
			},
			{
				show: true,
				productCode: "1040060",
				name: "ABUTILON C21",
				img: Images1 + '/abutilon-62b1d39dcd060-300x225.jpeg',
				stockUn: "Qtd",
				qtdPallet: 10,
				family: "FLOR EM VASO",
				showRecomendation: true,
				recomendation: {
					quantity : 1,
					unitPrice:  1840
				},
				center: [
					{
						show: true,
						name: "SAO PAULO",
						stockLabel: '1 Qtd',
						stock: 1,
						listPrice: 1540,
						taxPrice : 200,
						jurosPrice : 100,
						campaignPrice : 1790,
						showLastBuy: true,
						showCart: false,
						lastBuy: "10/05/2022",
						leadTime: 5,
						quantity: 0,
						discount: 0,
						totalPrice: 0,
						showReposition: true,
						reposition:{
                			culture: 'Quantidade disponivel no pedido: 1 de 1',
                			order: '00011259 - KAIQUE CIRTO',
                			date: '28/05/2022',
                			margin: 20,
                			quantity: 1,
                			price: 1237.5
						},
					},
					{
						show: true,
						name: "RIO DE JANEIRO",
						stockLabel: '2 Qtd',
						stock: 2,
						listPrice: 1540,
						taxPrice : 200,
						jurosPrice : 100,
						campaignPrice : 1790,
						showLastBuy: true,
						showCart: false,
						lastBuy: "10/05/2022",
						leadTime: 5,
						quantity: 0,
						discount: 0,
						totalPrice: 0
					},
				]
			},
			{
				show: true,
				productCode: "303315004",
				name: "Maço Folhagem Antúrio (Linha Poética)",
				img: Images1 + '/MACO-FOLHAGEM-ANTURIO-1-300x200.jpg',
				stockUn: "Qtd",
				qtdPallet: 7,
				family: "FOLHAGEM",
				showRecomendation: true,
				recomendation: {
					quantity : 1,
					unitPrice: 2191.15
				},
				center: [
					{
						show: true,
						name: "SAO PAULO",
						stockLabel: '1 Qtd',
						stock: 1,
						listPrice: 2001.15,
						taxPrice : 100,
						jurosPrice : 50,
						campaignPrice : 2171.15,
						showLastBuy: true,
						showCart: false,
						lastBuy: "10/05/2022",
						leadTime: 5,
						quantity: 0,
						discount: 0,
						totalPrice: 0,
						showReposition: true,
						reposition:{
                			culture: 'Quantidade disponivel no pedido: 1 de 1',
                			order: '00011259 - KAIQUE CIRTO',
                			date: '28/05/2022',
                			margin: 20,
                			quantity: 1,
                			price: 1237.5
						},
					},
					{
						show: true,
						name: "RIO DE JANEIRO",
						stockLabel: '2 Qtd',
						stock: 2,
						listPrice: 2001.15,
						taxPrice : 100,
						jurosPrice : 50,
						campaignPrice : 2171.15,
						showLastBuy: true,
						showCart: false,
						lastBuy: "10/05/2022",
						leadTime: 5,
						quantity: 0,
						discount: 0,
						totalPrice: 0
					},
				]
			},
			{
				show: true,
				productCode: "303315004",
				name: "ALSTROEMERIA AKEMI 080 CM",
				img: Images1 + '/alst-akemi-62b094dcc24ff-300x225.jpeg',
				stockUn: "Qtd",
				qtdPallet: 7,
				family: "FLOR DE CORTE",
				showRecomendation: true,
				recomendation: {
					quantity : 1,
					unitPrice: 2191.15
				},
				center: [
					{
						show: true,
						name: "SAO PAULO",
						stockLabel: '1 Qtd',
						stock: 1,
						listPrice: 2001.15,
						taxPrice : 100,
						jurosPrice : 50,
						campaignPrice : 2171.15,
						showLastBuy: true,
						showCart: false,
						lastBuy: "10/05/2022",
						leadTime: 5,
						quantity: 0,
						discount: 0,
						totalPrice: 0,
						showReposition: true,
						reposition:{
                			culture: 'Quantidade disponivel no pedido: 1 de 1',
                			order: '00011259 - KAIQUE CIRTO',
                			date: '28/05/2022',
                			margin: 20,
                			quantity: 1,
                			price: 1237.5
						},
					},
					{
						show: true,
						name: "RIO DE JANEIRO",
						stockLabel: '2 Qtd',
						stock: 2,
						listPrice: 2001.15,
						taxPrice : 100,
						jurosPrice : 50,
						campaignPrice : 2171.15,
						showLastBuy: true,
						showCart: false,
						lastBuy: "10/05/2022",
						leadTime: 5,
						quantity: 0,
						discount: 0,
						totalPrice: 0
					},
				]
			},
		];
}
const ALZData = () =>  {
	return [
			{
				show: true,
				productCode: "375012",
				name: "FERT SSP 19 GR - GRANEL",
				stockUn: "KG",
				qtdPallet: 200,
				family: "CIBRAFERTIL",
				showRecomendation: true,
				recomendation: {
					quantity : 200,
					unitPrice:  287.00
				},
				center: [
					{
						show: true,
						name: "SAO PAULO",
						stockLabel: '600 Kg',
						stock: 600,
						listPrice: 280.00,
						taxPrice : 20.32,
						jurosPrice : 12.43,
						campaignPrice : 265,
						showLastBuy: false,
						showCart: false,
						leadTime: 5,
						quantity: 0,
						discount: 0,
						totalPrice: 0,
						showReposition: true,
						reposition:{
                			culture: 'Quantidade disponivel no pedido: 400 de 600',
                			order: '00011259 - KAIQUE CIRTO',
                			date: '28/05/2022',
                			margin: 10,
                			quantity: 600,
                			price: 288
						},
					},
					{
						show: true,
						name: "RIO DE JANEIRO",
						stockLabel: '600 Kg',
						stock: 600,
						listPrice: 280.00,
						taxPrice : 20.32,
						jurosPrice : 12.43,
						campaignPrice : 265,
						showLastBuy: true,
						showCart: false,
						lastBuy: "30/03/2023",
						leadTime: 5,
						quantity: 0,
						discount: 0,
						totalPrice: 0,
						showReposition: false
					},
				]
			},			
			{
				show: true,
				productCode: "386604",
				name: "FERT 00.18.00 GR - GRANEL",
				stockUn: "KG",
				qtdPallet: 62,
				family: "FERTIPAR",
				showRecomendation: true,
				recomendation: {
					quantity : 200,
					unitPrice:  320.00
				},
				center: [
					{
						show: true,
						name: "SAO PAULO",
						stockLabel: '600 Kg',
						stock: 600,
						listPrice: 330.00,
						taxPrice : 20.32,
						jurosPrice : 12.43,
						campaignPrice : 265,
						showLastBuy: true,
						showCart: false,
						lastBuy: "30/04/2023",
						leadTime: 5,
						quantity: 0,
						discount: 0,
						totalPrice: 0,
						showReposition: true,
						reposition:{
                			culture: 'Quantidade disponivel no pedido: 120 de 332',
                			order: '00011259 - KAIQUE CIRTO',
                			date: '28/05/2022',
                			margin: 10,
                			quantity: 600,
                			price: 288
						},
					},
					{
						show: true,
						name: "RIO DE JANEIRO",
						stockLabel: '600 Kg',
						stock: 600,
						listPrice: 330.00,
						taxPrice : 20.32,
						jurosPrice : 12.43,
						campaignPrice : 265,
						showCart: false,
						leadTime: 5,
						quantity: 0,
						discount: 0,
						totalPrice: 0,
						showReposition: false
					},
				]
			},		
			{
				show: true,
				productCode: "375012",
				name: "FERT UREIA GRANULADA - BIG BAG",
				stockUn: "BB",
				qtdPallet: 20,
				family: "FOSNOR",
				showRecomendation: true,
				recomendation: {
					quantity : 180,
					unitPrice:  530.00
				},
				center: [
					{
						show: true,
						name: "SAO PAULO",
						stockLabel: '200 BB',
						stock: 200,
						listPrice: 340.00,
						taxPrice : 76.32,
						jurosPrice : 52.43,
						campaignPrice : 330,
						showLastBuy: false,
						showCart: false,
						leadTime: 5,
						quantity: 0,
						discount: 0,
						totalPrice: 0,
						showReposition: false
					},
					{
						show: true,
						name: "RIO DE JANEIRO",
						stockLabel: '200 BB',
						stock: 200,
						listPrice: 340.00,
						taxPrice : 76.32,
						jurosPrice : 52.43,
						campaignPrice : 330,
						showCart: false,
						leadTime: 5,
						quantity: 0,
						discount: 0,
						totalPrice: 0,
						showReposition: true,
						reposition:{
                			culture: 'Quantidade disponivel no pedido: 40 de 180',
                			order: '00011259 - KAIQUE CIRTO',
                			date: '28/05/2022',
                			margin: 10,
                			quantity: 120,
                			price: 518.40
						},
					},
				]
			},		
			{
				show: true,
				productCode: "301406",
				name: "FERT KCL 00.00.60 - GRANEL",
				stockUn: "Kg",
				qtdPallet: 1000,
				family: "FERTIPAR",
				showRecomendation: true,
				recomendation: {
					quantity : 180,
					unitPrice:  530.00
				},
				center: [
					{
						show: true,
						name: "SAO PAULO",
						stockLabel: '200 Kg',
						stock: 200,
						listPrice: 620.00,
						taxPrice : 76.32,
						jurosPrice : 52.43,
						campaignPrice : 330,
						showLastBuy: false,
						showCart: false,
						leadTime: 5,
						quantity: 0,
						discount: 0,
						totalPrice: 0,
						showReposition: false
					},
					{
						show: true,
						name: "RIO DE JANEIRO",
						stockLabel: '200 Kg',
						stock: 200,
						listPrice: 620.00,
						taxPrice : 76.32,
						jurosPrice : 52.43,
						campaignPrice : 330,
						showCart: false,
						leadTime: 5,
						quantity: 0,
						discount: 0,
						totalPrice: 0,
						showReposition: true,
						reposition:{
                			culture: 'Quantidade disponivel no pedido: 1250 de 2750',
                			order: '00011259 - KAIQUE CIRTO',
                			date: '28/05/2022',
                			margin: 10,
                			quantity: 120,
                			price: 604.40
						},
					},
				]
			},		
			{
				show: true,
				productCode: "386466",
				name: "FERT TSP GRANULADO 45% P205 CA-10% - BB",
				stockUn: "BB",
				qtdPallet: 1,
				family: "FERT TOCANTINS",
				showRecomendation: false,
				recomendation: {
					quantity : 180,
					unitPrice:  530.00
				},
				center: [
					{
						show: true,
						name: "SAO PAULO",
						stockLabel: '1 BB',
						stock: 200,
						listPrice: 840.00,
						taxPrice : 76.32,
						jurosPrice : 52.43,
						campaignPrice : 330,
						showLastBuy: false,
						showCart: false,
						leadTime: 5,
						quantity: 0,
						discount: 0,
						totalPrice: 0,
						showReposition: false
					},
					{
						show: true,
						name: "RIO DE JANEIRO",
						stockLabel: '1 BB',
						stock: 200,
						listPrice: 840.00,
						taxPrice : 76.32,
						jurosPrice : 52.43,
						campaignPrice : 330,
						showCart: false,
						leadTime: 5,
						quantity: 0,
						discount: 0,
						totalPrice: 0,
						showReposition: false
					},
				]
			}
		];
}
const FacholiData = () => {
  return [
    {
      show: true,
      productCode: "20200081_1",
      name: "POTENMIX 40 30KG",
      stockUn: "UN",
      qtdPallet: 200,
      family: "SUPLEMENTO",
      showRecomendation: true,
      recomendation: {
        quantity: 200,
        unitPrice: 287.0,
      },
      center: [
        {
          show: true,
          name: "CUIABA",
          madeFor: "Santo Anastácio",
          deliveryFor: "Centro de Distribuição",
          stockLabel: "600 Kg",
          stock: 600,
          listPrice: 280.0,
          taxPrice: 7,
		  outboundFreight: 12,
		  transferFreight: 9,
          comission: 4,
          baseComission: 4,
          jurosPrice: 12.43,
          campaignPrice: 265,
          showLastBuy: false,
          showCart: false,
          leadTime: 5,
          quantity: 0,
          discount: 0,
          totalPrice: 0,
          showReposition: true,
          reposition: {
            culture: "Quantidade disponivel no pedido: 400 de 600",
            order: "00011259 - KAIQUE CIRTO",
            date: "28/05/2022",
            margin: 10,
            quantity: 600,
            price: 288,
          },
        },
        {
          show: true,
          name: "VILHENA",
          madeFor: "Santo Anastácio",
          deliveryFor: "Centro de Distribuição",
          stockLabel: "600 Kg",
          stock: 600,
          listPrice: 280.0,
          taxPrice: 7,
		  outboundFreight: 12,
		  transferFreight: 9,
          comission: 4,
          baseComission: 4,
          jurosPrice: 12.43,
          campaignPrice: 265,
          showLastBuy: true,
          showCart: false,
          lastBuy: "30/03/2023",
          leadTime: 5,
          quantity: 0,
          discount: 0,
          totalPrice: 0,
          showReposition: false,
        },
      ],
    },
    {
      show: true,
      productCode: "2060093_1",
      name: "BRBEEF 14 30KG",
      stockUn: "UN",
      qtdPallet: 62,
      family: "RAÇÕES",
      showRecomendation: true,
      recomendation: {
        quantity: 200,
        unitPrice: 320.0,
      },
      center: [
        {
          show: true,
          name: "CUIABÁ",
          madeFor: "Santo Anastácio",
          deliveryFor: "Centro de Distribuição",
          stockLabel: "600 Kg",
          stock: 600,
          listPrice: 330.0,
          taxPrice: 7,
		  outboundFreight: 12,
		  transferFreight: 9,
          comission: 4,
          baseComission: 4,
          jurosPrice: 12.43,
          campaignPrice: 265,
          showLastBuy: true,
          showCart: false,
          lastBuy: "30/04/2023",
          leadTime: 5,
          quantity: 0,
          discount: 0,
          totalPrice: 0,
          showReposition: true,
          reposition: {
            culture: "Quantidade disponivel no pedido: 120 de 332",
            order: "00011259 - KAIQUE CIRTO",
            date: "28/05/2022",
            margin: 10,
            quantity: 600,
            price: 288,
          },
        },
        {
          show: true,
          name: "PORTO VELHO",
          madeFor: "Santo Anastácio",
          deliveryFor: "Centro de Distribuição",
          stockLabel: "600 Kg",
          stock: 600,
          listPrice: 330.0,
          taxPrice: 7,
		  outboundFreight: 12,
		  transferFreight: 9,
          comission: 4,
          baseComission: 4,
          jurosPrice: 12.43,
          campaignPrice: 265,
          showCart: false,
          leadTime: 5,
          quantity: 0,
          discount: 0,
          totalPrice: 0,
          showReposition: false,
        },
      ],
    },
    {
      show: true,
      productCode: "20200034_1",
      name: "POTENMIX AGUAS 30KG",
      stockUn: "UN",
      qtdPallet: 20,
      family: "SUPLEMENTO",
      showRecomendation: true,
      recomendation: {
        quantity: 180,
        unitPrice: 530.0,
      },
      center: [
        {
          show: true,
          name: "CUIABÁ",
          madeFor: "Santo Anastácio",
          deliveryFor: "Centro de Distribuição",
          stockLabel: "200 UN",
          stock: 200,
          listPrice: 340.0,
          taxPrice: 7,
		  outboundFreight: 12,
		  transferFreight: 9,
          comission: 4,
          baseComission: 4,
          jurosPrice: 52.43,
          campaignPrice: 330,
          showLastBuy: false,
          showCart: false,
          leadTime: 5,
          quantity: 0,
          discount: 0,
          totalPrice: 0,
          showReposition: false,
        },
        {
          show: true,
          name: "ÁGUA BOA",
          madeFor: "Santo Anastácio",
          deliveryFor: "Centro de Distribuição",
          stockLabel: "200 KG",
          stock: 200,
          listPrice: 340.0,
          taxPrice: 7,
		  outboundFreight: 12,
		  transferFreight: 9,
          comission: 4,
          baseComission: 4,
          jurosPrice: 52.43,
          campaignPrice: 330,
          showCart: false,
          leadTime: 5,
          quantity: 0,
          discount: 0,
          totalPrice: 0,
          showReposition: true,
          reposition: {
            culture: "Quantidade disponivel no pedido: 40 de 180",
            order: "00011259 - KAIQUE CIRTO",
            date: "28/05/2022",
            margin: 10,
            quantity: 120,
            price: 518.4,
          },
        },
      ],
    },
    {
      show: true,
      productCode: "2020083_1",
      name: "POTENMIX PASTO 320 30KG",
      stockUn: "UN",
      qtdPallet: 1000,
      family: "SUPLEMENTO",
      showRecomendation: true,
      recomendation: {
        quantity: 180,
        unitPrice: 530.0,
      },
      center: [
        {
          show: true,
          name: "ARAGUAÍNA",
          madeFor: "Santo Anastácio",
          deliveryFor: "Centro de Distribuição",
          stockLabel: "200 Kg",
          stock: 200,
          listPrice: 620.0,
          taxPrice: 7,
		  outboundFreight: 12,
		  transferFreight: 9,
          comission: 4,
          baseComission: 4,
          jurosPrice: 52.43,
          campaignPrice: 330,
          showLastBuy: false,
          showCart: false,
          leadTime: 5,
          quantity: 0,
          discount: 0,
          totalPrice: 0,
          showReposition: false,
        },
        {
          show: true,
          name: "MARABÁ",
          madeFor: "Santo Anastácio",
          deliveryFor: "Centro de Distribuição",
          stockLabel: "200 Kg",
          stock: 200,
          listPrice: 620.0,
          taxPrice: 7,
		  outboundFreight: 12,
		  transferFreight: 9,
          comission: 4,
          baseComission: 4,
          jurosPrice: 52.43,
          campaignPrice: 330,
          showCart: false,
          leadTime: 5,
          quantity: 0,
          discount: 0,
          totalPrice: 0,
          showReposition: true,
          reposition: {
            culture: "Quantidade disponivel no pedido: 1250 de 2750",
            order: "00011259 - KAIQUE CIRTO",
            date: "28/05/2022",
            margin: 10,
            quantity: 120,
            price: 604.4,
          },
        },
      ],
    },
    {
      show: true,
      productCode: "20600097_1",
      name: "BRNILK 20 30KG",
      stockUn: "UN",
      qtdPallet: 42,
      family: "RAÇÕES",
      showRecomendation: false,
      recomendation: {
        quantity: 180,
        unitPrice: 530.0,
      },
      center: [
        {
          show: true,
          name: "CUIABÁ",
          madeFor: "Santo Anastácio",
          deliveryFor: "Centro de Distribuição",
          stockLabel: "200 KG",
          stock: 200,
          listPrice: 840.0,
          taxPrice: 7,
		  outboundFreight: 12,
		  transferFreight: 9,
          comission: 4,
          baseComission: 4,
          jurosPrice: 52.43,
          campaignPrice: 330,
          showLastBuy: false,
          showCart: false,
          leadTime: 5,
          quantity: 0,
          discount: 0,
          totalPrice: 0,
          showReposition: false,
        },
        {
          show: true,
          name: "PORTO VELHO",
          madeFor: "Santo Anastácio",
          deliveryFor: "Centro de Distribuição",
          stockLabel: "200 KG",
          stock: 200,
          listPrice: 840.0,
          taxPrice: 7,
		  outboundFreight: 12,
		  transferFreight: 9,
          comission: 4,
          baseComission: 4,
          jurosPrice: 52.43,
          campaignPrice: 330,
          showCart: false,
          leadTime: 5,
          quantity: 0,
          discount: 0,
          totalPrice: 0,
          showReposition: false,
        },
      ],
    },
  ];
};
export {
  FacholiData, 
  ALZData,
  VeilingData,
  fertiSystemData,
  plantaeData,
  vittiaData,
  javData,
  unitFertData,
  forusData,
  verderaData,
  viterData,
  iharaData,
  haraldData,
  venezaData,
  violeteraData,
  itajaData,
};